# Generated by Django 3.2.9 on 2021-12-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211214_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
