# Generated by Django 3.2.9 on 2021-12-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='names',
            new_name='name',
        ),
    ]
