# Generated by Django 3.2.9 on 2021-12-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211216_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='restaurant_name',
            field=models.CharField(default='Barreto Cafe', max_length=100),
            preserve_default=False,
        ),
    ]
