# Generated by Django 3.2.9 on 2021-12-12 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_restaurant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('picture', models.TextField(max_length=100)),
                ('notifications', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('people', models.IntegerField()),
                ('occasion', models.CharField(choices=[('A', 'Anniversary'), ('B', 'Birthday'), ('C', 'Celebration'), ('D', 'Date Night'), ('M', 'Business Meeting')], default='C', max_length=1)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.user'),
        ),
    ]
