# Generated by Django 3.2.9 on 2021-12-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20211214_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='star_rating',
            field=models.IntegerField(),
        ),
    ]
